### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by jcstanaway** [evanhuang8/iorejson#2]
It appears that while iorejson utilizes ioredis, from the documentation it appears that iorejson does not support a Redis cluster and does not support the other Redis commands.  Is that correct?

If not using clustering, I would have to create two clients:  one using ioredis for other commands/data-types and one using iorejson for managing JSON data types.  Correct?

Are there any plans to extend iorejson to support Redis clusters and the rest of the Redis command set?

**Comment by evanhuang8** [comment]
It's correct that it does NOT support redis cluster at the moment. It's also unclear whether the rejson module itself is suitable for cluster use yet, but I suppose it should be doable since the underlying client is transparent.

As for other regular redis commands, you can access the underlying client directly:

```
var Rejson = require('iorejson');

var instance = new Rejson();
yield instance.connect()
var client = instance.client; // the ioredis client

client.get('foo'); // do your work here
```

**Comment by jcstanaway** [comment]
Okay, thanks for the clarification.
